// Generated by CoffeeScript 1.8.0
if (window.HG == null) {
  window.HG = {};
}

HG.DateMarker = (function() {
  var MONTH_NAMES;

  MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

  function DateMarker(date, timeline) {
    this._date = date;
    this._timeline = timeline;
    this._div = null;
    this.updateView(true);
  }

  DateMarker.prototype.updateView = function(show) {
    if (show) {
      if (this._div == null) {
        this._div = document.createElement("div");
        this._div.id = "tl_year_" + this._date.getFullYear();
        this._div.className = "tl_datemarker";
        this._div.innerHTML = this._date.getFullYear();
        this._div.style.left = this._timeline.dateToPosition(this._date) + "px";
        this._div.style.display = "none";
        this._timeline.getCanvas().appendChild(this._div);
        return $(this._div).fadeIn(200);
      } else {
        return this._div.style.left = this._timeline.dateToPosition(this._date) + "px";
      }
    } else {
      if (this._div != null) {
        return $(this._div).fadeOut(200, function() { $(this).remove(); });
      }
    }
  };

  DateMarker.prototype.getDate = function() {
    return this._date;
  };

  DateMarker.prototype.getDiv = function() {
    return this._div;
  };

  DateMarker.prototype.setDate = function(date) {
    return this._date = date;
  };

  DateMarker.prototype.daysInMonth = function(month, year) {
    return new Date(year, month + 1, 0).getDate();
  };

  return DateMarker;

})();
